-- ==============================================================================
-- PATCH_FILE_001.sql - Service Center Tables (Vehicle, Job)
-- ==============================================================================
-- Adds Vehicle and Job tables for the Smitty service center.
-- JobPurchase is created in PATCH_FILE_002.sql (after Purchase table exists).
--
-- Prerequisites: schema.sql base tables (customer) must exist.
--
-- Usage:
--   psql -U smitty -d smitty_services -f database/PATCH_FILE_001.sql
--
-- Safe to re-run: all statements use IF NOT EXISTS.
-- ==============================================================================

BEGIN;

-- ------------------------------------------------------------------------------
-- Vehicle: commercial vehicles registered for service
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vehicle (
    vehicle_id    SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id   VARCHAR(10)  NOT NULL REFERENCES customer(customer_id),
    vin           VARCHAR(17)  NOT NULL,
    description   VARCHAR(200) NOT NULL,
    year          SMALLINT,
    make          VARCHAR(60),
    model         VARCHAR(60),
    license_plate VARCHAR(20),
    notes         TEXT,
    UNIQUE(vin)
);

-- ------------------------------------------------------------------------------
-- Job: service/repair engagement for a vehicle
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS job (
    job_id              SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id         VARCHAR(10)  NOT NULL REFERENCES customer(customer_id),
    vehicle_id          SMALLINT     NOT NULL REFERENCES vehicle(vehicle_id),
    service_description TEXT         NOT NULL,
    status              VARCHAR(30)  NOT NULL DEFAULT 'New',
    created_date        DATE         NOT NULL DEFAULT CURRENT_DATE,
    started_date        DATE,
    completed_date      DATE,
    estimated_cost      REAL,
    actual_cost         REAL,
    notes               TEXT
);

-- Valid statuses: New, In Progress, Waiting Parts, Road Test Pending, Complete

-- ------------------------------------------------------------------------------
-- Indexes
-- ------------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_vehicle_customer_id ON vehicle(customer_id);
CREATE INDEX IF NOT EXISTS idx_vehicle_vin         ON vehicle(vin);
CREATE INDEX IF NOT EXISTS idx_job_customer_id     ON job(customer_id);
CREATE INDEX IF NOT EXISTS idx_job_vehicle_id      ON job(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_job_status          ON job(status);
CREATE INDEX IF NOT EXISTS idx_job_created_date    ON job(created_date);

COMMIT;
