-- ==============================================================================
-- PATCH_FILE_002.sql - Purchase and PurchaseItem Tables
-- ==============================================================================
-- Adds Purchase (supplier purchase orders) and PurchaseItem (line items).
-- Updates job_purchase to reference purchase instead of order.
--
-- Prerequisites: PATCH_FILE_001.sql (vehicle, job tables) must be applied first.
--
-- Usage:
--   psql -U smitty -d smitty_services -f database/PATCH_FILE_002.sql
--
-- Safe to re-run: all statements use IF NOT EXISTS / IF EXISTS checks.
-- ==============================================================================

BEGIN;

-- ------------------------------------------------------------------------------
-- Purchase: supplier purchase order for parts/supplies
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS purchase (
    purchase_id    SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    supplier_id    SMALLINT     NOT NULL REFERENCES supplier(supplier_id),
    purchase_date  DATE         NOT NULL DEFAULT CURRENT_DATE,
    expected_date  DATE,
    received_date  DATE,
    status         VARCHAR(30)  NOT NULL DEFAULT 'New',
    total_cost     REAL,
    notes          TEXT
);

-- Valid statuses: New, Ordered, Partial, Received, Cancelled

-- ------------------------------------------------------------------------------
-- PurchaseItem: line items on a purchase (product, cost, quantity)
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS purchase_item (
    purchase_id SMALLINT NOT NULL REFERENCES purchase(purchase_id),
    product_id  SMALLINT NOT NULL REFERENCES product(product_id),
    unit_cost   REAL     NOT NULL,
    quantity    SMALLINT NOT NULL,
    PRIMARY KEY (purchase_id, product_id)
);

-- ------------------------------------------------------------------------------
-- Migrate job_purchase from order_id to purchase_id
-- ------------------------------------------------------------------------------
-- Drop the old job_purchase table (linked to order) and recreate linked to purchase.
-- If you have existing data in job_purchase, back it up before running this patch.

DROP TABLE IF EXISTS job_purchase;

CREATE TABLE IF NOT EXISTS job_purchase (
    job_id      SMALLINT NOT NULL REFERENCES job(job_id),
    purchase_id SMALLINT NOT NULL REFERENCES purchase(purchase_id),
    PRIMARY KEY (job_id, purchase_id)
);

-- ------------------------------------------------------------------------------
-- Indexes
-- ------------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_purchase_supplier_id  ON purchase(supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_status       ON purchase(status);
CREATE INDEX IF NOT EXISTS idx_purchase_item_product ON purchase_item(product_id);

COMMIT;
