-- ==============================================================================
-- Smitty Services - Database Schema (PostgreSQL)
-- ==============================================================================
-- Northwind-based schema for the Smitty Services application.
-- Run this script to create all tables, indexes, and constraints.
--
-- Usage:
--   psql -U smitty -d smitty_services -f schema.sql
-- ==============================================================================

BEGIN;

-- ------------------------------------------------------------------------------
-- Reference Tables
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS region (
    region_id       SMALLINT    PRIMARY KEY,
    region_description VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS territory (
    territory_id          VARCHAR(20)  PRIMARY KEY,
    territory_description VARCHAR(60)  NOT NULL,
    region_id             SMALLINT     NOT NULL REFERENCES region(region_id)
);

CREATE TABLE IF NOT EXISTS us_state (
    state_id     SMALLINT    PRIMARY KEY,
    state_name   VARCHAR(100),
    state_abbr   VARCHAR(2),
    state_region VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS category (
    category_id   SMALLINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR(80) NOT NULL,
    description   TEXT,
    picture       BYTEA
);

CREATE TABLE IF NOT EXISTS supplier (
    supplier_id   SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_name  VARCHAR(80)  NOT NULL,
    contact_name  VARCHAR(60),
    contact_title VARCHAR(60),
    address       VARCHAR(120),
    city          VARCHAR(40),
    region        VARCHAR(40),
    postal_code   VARCHAR(20),
    country       VARCHAR(40),
    phone         VARCHAR(48),
    fax           VARCHAR(48),
    homepage      TEXT
);

CREATE TABLE IF NOT EXISTS shipper (
    shipper_id   SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_name VARCHAR(80)  NOT NULL,
    phone        VARCHAR(48)
);

-- ------------------------------------------------------------------------------
-- Customer Tables
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS customer_demographic (
    customer_type_id VARCHAR(10) PRIMARY KEY,
    customer_desc    TEXT
);

CREATE TABLE IF NOT EXISTS customer (
    customer_id   VARCHAR(10)  PRIMARY KEY,
    company_name  VARCHAR(80)  NOT NULL,
    contact_name  VARCHAR(60),
    contact_title VARCHAR(60),
    address       VARCHAR(120),
    city          VARCHAR(40),
    region        VARCHAR(40),
    postal_code   VARCHAR(20),
    country       VARCHAR(40),
    phone         VARCHAR(48),
    fax           VARCHAR(48)
);

CREATE TABLE IF NOT EXISTS customer_customer_demo (
    customer_id      VARCHAR(10) NOT NULL REFERENCES customer(customer_id),
    customer_type_id VARCHAR(10) NOT NULL REFERENCES customer_demographic(customer_type_id),
    PRIMARY KEY (customer_id, customer_type_id)
);

-- ------------------------------------------------------------------------------
-- Employee Tables
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS employee (
    employee_id       SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    last_name         VARCHAR(40)  NOT NULL,
    first_name        VARCHAR(40)  NOT NULL,
    title             VARCHAR(60),
    title_of_courtesy VARCHAR(50),
    birth_date        DATE,
    hire_date         DATE,
    address           VARCHAR(120),
    city              VARCHAR(40),
    region            VARCHAR(40),
    postal_code       VARCHAR(20),
    country           VARCHAR(40),
    home_phone        VARCHAR(48),
    extension         VARCHAR(8),
    photo             BYTEA,
    notes             TEXT,
    photo_path        VARCHAR(255),
    reports_to        SMALLINT     REFERENCES employee(employee_id)
);

CREATE TABLE IF NOT EXISTS employee_territory (
    employee_id  SMALLINT    NOT NULL REFERENCES employee(employee_id),
    territory_id VARCHAR(20) NOT NULL REFERENCES territory(territory_id),
    PRIMARY KEY (employee_id, territory_id)
);

-- ------------------------------------------------------------------------------
-- Product Table
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS product (
    product_id       SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name     VARCHAR(80)  NOT NULL,
    supplier_id      SMALLINT     REFERENCES supplier(supplier_id),
    category_id      SMALLINT     REFERENCES category(category_id),
    quantity_per_unit VARCHAR(40),
    unit_price       REAL,
    units_in_stock   SMALLINT,
    units_on_order   SMALLINT,
    reorder_level    SMALLINT,
    discontinued     INTEGER      NOT NULL DEFAULT 0
);

-- ------------------------------------------------------------------------------
-- Order Tables
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "order" (
    order_id         SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id      VARCHAR(10)  REFERENCES customer(customer_id),
    employee_id      SMALLINT     REFERENCES employee(employee_id),
    order_date       DATE,
    required_date    DATE,
    shipped_date     DATE,
    ship_via         SMALLINT     REFERENCES shipper(shipper_id),
    freight          REAL,
    ship_name        VARCHAR(80),
    ship_address     VARCHAR(120),
    ship_city        VARCHAR(40),
    ship_region      VARCHAR(40),
    ship_postal_code VARCHAR(20),
    ship_country     VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS order_detail (
    order_id   SMALLINT NOT NULL REFERENCES "order"(order_id),
    product_id SMALLINT NOT NULL REFERENCES product(product_id),
    unit_price REAL     NOT NULL,
    quantity   SMALLINT NOT NULL,
    discount   REAL     NOT NULL DEFAULT 0,
    PRIMARY KEY (order_id, product_id)
);

-- ------------------------------------------------------------------------------
-- Indexes for common queries
-- ------------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_customer_company_name   ON customer(company_name);
CREATE INDEX IF NOT EXISTS idx_order_customer_id       ON "order"(customer_id);
CREATE INDEX IF NOT EXISTS idx_order_employee_id       ON "order"(employee_id);
CREATE INDEX IF NOT EXISTS idx_order_order_date        ON "order"(order_date);
CREATE INDEX IF NOT EXISTS idx_order_ship_name         ON "order"(ship_name);
CREATE INDEX IF NOT EXISTS idx_order_detail_product_id ON order_detail(product_id);
CREATE INDEX IF NOT EXISTS idx_product_product_name    ON product(product_name);
CREATE INDEX IF NOT EXISTS idx_product_category_id     ON product(category_id);
CREATE INDEX IF NOT EXISTS idx_product_supplier_id     ON product(supplier_id);
CREATE INDEX IF NOT EXISTS idx_employee_last_name      ON employee(last_name);
CREATE INDEX IF NOT EXISTS idx_territory_region_id     ON territory(region_id);

COMMIT;
