-- ==============================================================================
-- Smitty Services - Database Schema (PostgreSQL)
-- ==============================================================================
-- Northwind-based schema for the Smitty Services application.
-- Uses standard Northwind plural table names (customers, orders, products, etc.)
-- Run this script to create all tables, indexes, and constraints.
--
-- Usage:
--   psql -U smitty -d smitty_services -f schema.sql
-- ==============================================================================

BEGIN;

-- ------------------------------------------------------------------------------
-- Reference Tables
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS regions (
    region_id       SMALLINT    PRIMARY KEY,
    region_description VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS territories (
    territory_id          VARCHAR(20)  PRIMARY KEY,
    territory_description VARCHAR(60)  NOT NULL,
    region_id             SMALLINT     NOT NULL REFERENCES regions(region_id)
);

CREATE TABLE IF NOT EXISTS us_states (
    state_id     SMALLINT    PRIMARY KEY,
    state_name   VARCHAR(100),
    state_abbr   VARCHAR(2),
    state_region VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS categories (
    category_id   SMALLINT    PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category_name VARCHAR(80) NOT NULL,
    description   TEXT,
    picture       BYTEA
);

CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id   SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_name  VARCHAR(80)  NOT NULL,
    contact_name  VARCHAR(60),
    contact_title VARCHAR(60),
    address       VARCHAR(120),
    city          VARCHAR(40),
    region        VARCHAR(40),
    postal_code   VARCHAR(20),
    country       VARCHAR(40),
    phone         VARCHAR(48),
    fax           VARCHAR(48),
    homepage      TEXT
);

CREATE TABLE IF NOT EXISTS shippers (
    shipper_id   SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    company_name VARCHAR(80)  NOT NULL,
    phone        VARCHAR(48)
);

-- ------------------------------------------------------------------------------
-- Customer Tables
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS customer_demographics (
    customer_type_id VARCHAR(10) PRIMARY KEY,
    customer_desc    TEXT
);

CREATE TABLE IF NOT EXISTS customers (
    customer_id   VARCHAR(10)  PRIMARY KEY,
    company_name  VARCHAR(80)  NOT NULL,
    contact_name  VARCHAR(60),
    contact_title VARCHAR(60),
    address       VARCHAR(120),
    city          VARCHAR(40),
    region        VARCHAR(40),
    postal_code   VARCHAR(20),
    country       VARCHAR(40),
    phone         VARCHAR(48),
    fax           VARCHAR(48)
);

CREATE TABLE IF NOT EXISTS customer_customer_demo (
    customer_id      VARCHAR(10) NOT NULL REFERENCES customers(customer_id),
    customer_type_id VARCHAR(10) NOT NULL REFERENCES customer_demographics(customer_type_id),
    PRIMARY KEY (customer_id, customer_type_id)
);

-- ------------------------------------------------------------------------------
-- Employee Tables
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS employees (
    employee_id       SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    last_name         VARCHAR(40)  NOT NULL,
    first_name        VARCHAR(40)  NOT NULL,
    title             VARCHAR(60),
    title_of_courtesy VARCHAR(50),
    birth_date        DATE,
    hire_date         DATE,
    address           VARCHAR(120),
    city              VARCHAR(40),
    region            VARCHAR(40),
    postal_code       VARCHAR(20),
    country           VARCHAR(40),
    home_phone        VARCHAR(48),
    extension         VARCHAR(8),
    photo             BYTEA,
    notes             TEXT,
    photo_path        VARCHAR(255),
    reports_to        SMALLINT     REFERENCES employees(employee_id)
);

CREATE TABLE IF NOT EXISTS employee_territories (
    employee_id  SMALLINT    NOT NULL REFERENCES employees(employee_id),
    territory_id VARCHAR(20) NOT NULL REFERENCES territories(territory_id),
    PRIMARY KEY (employee_id, territory_id)
);

-- ------------------------------------------------------------------------------
-- Product Table
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS products (
    product_id       SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_name     VARCHAR(80)  NOT NULL,
    supplier_id      SMALLINT     REFERENCES suppliers(supplier_id),
    category_id      SMALLINT     REFERENCES categories(category_id),
    quantity_per_unit VARCHAR(40),
    unit_price       REAL,
    units_in_stock   SMALLINT,
    units_on_order   SMALLINT,
    reorder_level    SMALLINT,
    discontinued     INTEGER      NOT NULL DEFAULT 0
);

-- ------------------------------------------------------------------------------
-- Order Tables
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS orders (
    order_id         SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id      VARCHAR(10)  REFERENCES customers(customer_id),
    employee_id      SMALLINT     REFERENCES employees(employee_id),
    order_date       DATE,
    required_date    DATE,
    shipped_date     DATE,
    ship_via         SMALLINT     REFERENCES shippers(shipper_id),
    freight          REAL,
    ship_name        VARCHAR(80),
    ship_address     VARCHAR(120),
    ship_city        VARCHAR(40),
    ship_region      VARCHAR(40),
    ship_postal_code VARCHAR(20),
    ship_country     VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS order_details (
    order_id   SMALLINT NOT NULL REFERENCES orders(order_id),
    product_id SMALLINT NOT NULL REFERENCES products(product_id),
    unit_price REAL     NOT NULL,
    quantity   SMALLINT NOT NULL,
    discount   REAL     NOT NULL DEFAULT 0,
    PRIMARY KEY (order_id, product_id)
);

-- ------------------------------------------------------------------------------
-- Service Center Tables
-- ------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS vehicles (
    vehicle_id    SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id   VARCHAR(10)  NOT NULL REFERENCES customers(customer_id),
    vin           VARCHAR(17)  NOT NULL,
    description   VARCHAR(200) NOT NULL,
    year          SMALLINT,
    make          VARCHAR(60),
    model         VARCHAR(60),
    license_plate VARCHAR(20),
    notes         TEXT,
    UNIQUE(vin)
);

CREATE TABLE IF NOT EXISTS jobs (
    job_id             SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id        VARCHAR(10)  NOT NULL REFERENCES customers(customer_id),
    vehicle_id         SMALLINT     NOT NULL REFERENCES vehicles(vehicle_id),
    service_description TEXT        NOT NULL,
    status             VARCHAR(30)  NOT NULL DEFAULT 'New',
    created_date       DATE         NOT NULL DEFAULT CURRENT_DATE,
    started_date       DATE,
    completed_date     DATE,
    estimated_cost     REAL,
    actual_cost        REAL,
    notes              TEXT
);

CREATE TABLE IF NOT EXISTS purchases (
    purchase_id    SMALLINT     PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    supplier_id    SMALLINT     NOT NULL REFERENCES suppliers(supplier_id),
    purchase_date  DATE         NOT NULL DEFAULT CURRENT_DATE,
    expected_date  DATE,
    received_date  DATE,
    status         VARCHAR(30)  NOT NULL DEFAULT 'New',
    total_cost     REAL,
    notes          TEXT
);

CREATE TABLE IF NOT EXISTS purchase_items (
    purchase_id SMALLINT NOT NULL REFERENCES purchases(purchase_id),
    product_id  SMALLINT NOT NULL REFERENCES products(product_id),
    unit_cost   REAL     NOT NULL,
    quantity    SMALLINT NOT NULL,
    PRIMARY KEY (purchase_id, product_id)
);

CREATE TABLE IF NOT EXISTS job_purchases (
    job_id      SMALLINT NOT NULL REFERENCES jobs(job_id),
    purchase_id SMALLINT NOT NULL REFERENCES purchases(purchase_id),
    PRIMARY KEY (job_id, purchase_id)
);

-- ------------------------------------------------------------------------------
-- Indexes for common queries
-- ------------------------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_customer_company_name   ON customers(company_name);
CREATE INDEX IF NOT EXISTS idx_order_customer_id       ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_order_employee_id       ON orders(employee_id);
CREATE INDEX IF NOT EXISTS idx_order_order_date        ON orders(order_date);
CREATE INDEX IF NOT EXISTS idx_order_ship_name         ON orders(ship_name);
CREATE INDEX IF NOT EXISTS idx_order_detail_product_id ON order_details(product_id);
CREATE INDEX IF NOT EXISTS idx_product_product_name    ON products(product_name);
CREATE INDEX IF NOT EXISTS idx_product_category_id     ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_product_supplier_id     ON products(supplier_id);
CREATE INDEX IF NOT EXISTS idx_employee_last_name      ON employees(last_name);
CREATE INDEX IF NOT EXISTS idx_territory_region_id     ON territories(region_id);

CREATE INDEX IF NOT EXISTS idx_vehicle_customer_id     ON vehicles(customer_id);
CREATE INDEX IF NOT EXISTS idx_vehicle_vin             ON vehicles(vin);
CREATE INDEX IF NOT EXISTS idx_job_customer_id         ON jobs(customer_id);
CREATE INDEX IF NOT EXISTS idx_job_vehicle_id          ON jobs(vehicle_id);
CREATE INDEX IF NOT EXISTS idx_job_status              ON jobs(status);
CREATE INDEX IF NOT EXISTS idx_job_created_date        ON jobs(created_date);
CREATE INDEX IF NOT EXISTS idx_purchase_supplier_id    ON purchases(supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_status         ON purchases(status);
CREATE INDEX IF NOT EXISTS idx_purchase_item_product   ON purchase_items(product_id);

COMMIT;
