#include "RevenueReport.h"
#include <cstdio>

RevenueReport::RevenueReport(const std::vector<RevenueSummary>& summaries,
                               const std::string& reportTitle,
                               const std::string& dateRange)
    : PdfReport(reportTitle)
    , summaries_(summaries)
    , dateRange_(dateRange)
    , grandTotal_(0.0)
    , totalOrders_(0) {
    for (const auto& s : summaries_) {
        grandTotal_ += s.totalRevenue;
        totalOrders_ += s.orderCount;
    }
}

void RevenueReport::generateContent() {
    drawSummaryCards();
    drawRevenueTable();
    drawNotes();
}

void RevenueReport::drawSummaryCards() {
    float y = contentTop();

    addTextBold("Report Period: " + dateRange_, 10, MARGIN_LEFT, y);
    y -= 30;

    float cardW = (contentWidth() - 20) / 3.0f;
    float cardH = 50;

    // Total Revenue card
    pdf_add_filled_rectangle(pdf_, currentPage_,
                             MARGIN_LEFT, y - cardH, cardW, cardH,
                             0.5f, PDF_RGB(0xf0, 0xf8, 0xff), PDF_RGB(0x4f, 0xc3, 0xf7));
    addText("Total Revenue", 8, MARGIN_LEFT + 8, y - 14, PDF_RGB(0x88, 0x88, 0x88));
    addTextBold(formatCurrency(grandTotal_), 16, MARGIN_LEFT + 8, y - 36, PDF_RGB(0x1a, 0x1a, 0x2e));

    // Total Orders card
    float card2X = MARGIN_LEFT + cardW + 10;
    pdf_add_filled_rectangle(pdf_, currentPage_,
                             card2X, y - cardH, cardW, cardH,
                             0.5f, PDF_RGB(0xf0, 0xff, 0xf0), PDF_RGB(0x66, 0xbb, 0x6a));
    addText("Total Orders", 8, card2X + 8, y - 14, PDF_RGB(0x88, 0x88, 0x88));
    addTextBold(std::to_string(totalOrders_), 16, card2X + 8, y - 36, PDF_RGB(0x1a, 0x1a, 0x2e));

    // Average Order Value card
    float card3X = card2X + cardW + 10;
    double avgVal = totalOrders_ > 0 ? grandTotal_ / totalOrders_ : 0.0;
    pdf_add_filled_rectangle(pdf_, currentPage_,
                             card3X, y - cardH, cardW, cardH,
                             0.5f, PDF_RGB(0xff, 0xf8, 0xf0), PDF_RGB(0xff, 0xa7, 0x26));
    addText("Avg Order Value", 8, card3X + 8, y - 14, PDF_RGB(0x88, 0x88, 0x88));
    addTextBold(formatCurrency(avgVal), 16, card3X + 8, y - 36, PDF_RGB(0x1a, 0x1a, 0x2e));
}

void RevenueReport::drawRevenueTable() {
    float y = contentTop() - 110;

    drawSectionTitle("Revenue Breakdown", y);
    y -= 20;

    std::vector<TableColumn> columns = {
        {"Period", 140, PDF_ALIGN_LEFT},
        {"Orders", 80, PDF_ALIGN_RIGHT},
        {"Revenue", 120, PDF_ALIGN_RIGHT},
        {"Avg Order", 120, PDF_ALIGN_RIGHT}
    };

    drawTableHeader(columns, y);
    y -= HEADER_ROW_HEIGHT;

    for (const auto& summary : summaries_) {
        y = checkPageBreak(y, ROW_HEIGHT * 2);

        std::vector<std::string> row = {
            summary.period,
            std::to_string(summary.orderCount),
            formatCurrency(summary.totalRevenue),
            formatCurrency(summary.averageOrderValue)
        };

        y = drawTableRow(columns, row, y);
    }

    // Grand total row
    y -= 10;
    drawHorizontalLine(y, 1.5f, PDF_RGB(0x16, 0x21, 0x3e));
    y -= 16;

    addTextBold("GRAND TOTAL", 10, MARGIN_LEFT + 4, y);

    char buf[32];
    snprintf(buf, sizeof(buf), "%d", totalOrders_);
    addTextBold(buf, 10, MARGIN_LEFT + 190, y);
    addTextBold(formatCurrency(grandTotal_), 10, MARGIN_LEFT + 300, y);
}

void RevenueReport::drawNotes() {
    float y = contentBottom() + 60;

    drawHorizontalLine(y + 10, 0.5f, PDF_RGB(0xcc, 0xcc, 0xcc));
    addText("Generated by Smitty Services - Imagery Business Systems, LLC",
            8, MARGIN_LEFT, y, PDF_RGB(0x99, 0x99, 0x99));
}
